setup(name='left-pad', 
    version='0.1',
    description='left-pad Python Package for Flask', 
    url='https://github.com/ectoglasses/left-pad', 
    author='Caspar', 
    author_email='', 
    license='MIT', 
    packages=['left-pad'],
    zip_safe=False)
